# Spring Batch Configuration
spring:
  # =============================================================
  # DataStax Astra Cassandra Connection Configuration
  # =============================================================
  cassandra:
    secure-connect-bundle: classpath:secure-connect-ecomnosql-db.zip
    username: "usernamess"
    password: "passwordss"
    keyspace-name: ecomnosql_keyspace
    schema-action: create-if-not-exists

  # =============================================================
  # Spring Batch Configuration
  # =============================================================
  datasource:
    url: jdbc:hsqldb:mem:batchdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true